name: ai_hokusai
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  adaptive_dialog: ^1.8.0+1
  cloud_firestore: ^3.4.7
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^1.0.4
  flutterfire_ui: ^0.4.3+8
  freezed_annotation: ^2.1.0
  go_router: ^4.4.1
  hooks_riverpod: ^1.0.4
  json_annotation: ^4.6.0
  modal_progress_hud_nsn: ^0.3.0
  rename: ^2.0.1
  retrofit: ^3.0.1+1
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3+1
flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ai_hokusai_icon_v1.png"
  remove_alpha_ios: true
