// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXkpP6xVBGjMEgJBJCHR-AFlgBZQoZJuQ',
    appId: '1:152856850111:web:9cc6c29312f09a836fa00a',
    messagingSenderId: '152856850111',
    projectId: 'ai-hokusai-release',
    authDomain: 'ai-hokusai-release.firebaseapp.com',
    storageBucket: 'ai-hokusai-release.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpHLlDD9G-Y8VEZ6jmhMR9rJOyoZB0f0U',
    appId: '1:152856850111:android:413457264644355e6fa00a',
    messagingSenderId: '152856850111',
    projectId: 'ai-hokusai-release',
    storageBucket: 'ai-hokusai-release.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABu3nNsscEHUGlz1P0EmK8n62we7Dxw-c',
    appId: '1:152856850111:ios:bf651d43945ebb286fa00a',
    messagingSenderId: '152856850111',
    projectId: 'ai-hokusai-release',
    storageBucket: 'ai-hokusai-release.appspot.com',
    iosClientId: '152856850111-viiltig46fjq97po5861ap25tan6rg0g.apps.googleusercontent.com',
    iosBundleId: 'com.ai.hokusai',
  );
}
